const express = require('express');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const session = require('express-session');
const passport = require('passport');
const passportConfig = require('./app/configs/passport-config');

const app = express();
const port = 3000;
const userRoute = require('./app/routes/user');
const authRoute = require('./app/routes/auth');
//process.env.root = __dirname;

const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const swaggerOpts = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
            title: 'Fypr Backend Starter',
            version: '1.0.0',
            description: 'API with autogenerated swagger doc',
        },
        "host": "localhost:3000"
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./app/routes/*.js'],
};

const swaggerSpecs = swaggerJsdoc(swaggerOpts);
//const swaggerDocument = require('./swagger.json');

//app.use(express.static('public'));
app.disable('x-powered-by');
app.use(cookieParser());
app.use(bodyParser.json({
    limit: '100kb',
}));
app.use(session({ secret: 'FyprBoilerplate', resave: false, saveUninitialized: false, cookie: { secure: false } }));
app.use(passport.initialize());

switch (passportConfig.strategy) {
    case "local":
        app.use(passport.session());
        require('./app/configs/passport-local')(passport);
        break;
    default:
        require('./app/configs/passport-jwt')(passport);
        break;
}

app.use(function (error, request, response, next) {
    console.error(error.stack);
    response.status(400).send(error.message);
});

app.get('/', (req, res) => res.send('Welcome to Fypr Backend Starter'))
app.use('/user', userRoute);
app.use('/auth', authRoute);

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpecs));

app.listen(port, () => console.log('Fypr Backend app is running'));